create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ZmodDigitizerCtrl_inst/U0/InstDataPath/InstDcoBufg_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {demod_data[0]} {demod_data[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Modulator_inst/symbols[0]} {Modulator_inst/symbols[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {Demodulator_inst/I[0]} {Demodulator_inst/I[1]} {Demodulator_inst/I[2]} {Demodulator_inst/I[3]} {Demodulator_inst/I[4]} {Demodulator_inst/I[5]} {Demodulator_inst/I[6]} {Demodulator_inst/I[7]} {Demodulator_inst/I[8]} {Demodulator_inst/I[9]} {Demodulator_inst/I[10]} {Demodulator_inst/I[11]} {Demodulator_inst/I[12]} {Demodulator_inst/I[13]} {Demodulator_inst/I[14]} {Demodulator_inst/I[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {Demodulator_inst/Q[0]} {Demodulator_inst/Q[1]} {Demodulator_inst/Q[2]} {Demodulator_inst/Q[3]} {Demodulator_inst/Q[4]} {Demodulator_inst/Q[5]} {Demodulator_inst/Q[6]} {Demodulator_inst/Q[7]} {Demodulator_inst/Q[8]} {Demodulator_inst/Q[9]} {Demodulator_inst/Q[10]} {Demodulator_inst/Q[11]} {Demodulator_inst/Q[12]} {Demodulator_inst/Q[13]} {Demodulator_inst/Q[14]} {Demodulator_inst/Q[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list demod_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets SampleClk]
